### ISSUE TITLE
build failing

### ISSUE THREAD

**Issue by pacaj2am** [joeycastillo/libros#1]
failing to build the project:

```Compiling .pio/build/pico/src/platform/pico/sleep.c.o
In file included from src/platform/pico/sleep.c:9:
/home/pi/.platformio/packages/framework-arduino-mbed/cores/arduino/mbed/targets/TARGET_RASPBERRYPI/TARGET_RP2040/pico-sdk/common/pico_stdlib/include/pico/stdlib.h:11:10: fatal error: pico/stdio.h: No such file or directory
   11 | #include "pico/stdio.h"
      |          ^~~~~~~~~~~~~~
compilation terminated.
*** [.pio/build/pico/src/platform/pico/sleep.c.o] Error 1
```

I am a bit lost with platfom.io and pipico. Could you point me, how to compile?

Might be nice to have binary builds in releases.

**Comment by joeycastillo** [comment]
Thanks for this comment, I'd just about forgotten about this quirk. So, I don't know what the issue is, but I do know that if you open the offending `stdlib.h` file in the mbed core and comment out line 11 (the `#include "pico/stdio.h"` line), it will compile. 

I'm not quite to the point of wanting to make binary releases; the book parser is still very fragile and I wouldn't want folks to think this is even pre-alpha software just yet. But the tweak above should get you building; let me know if it works!

**Comment by pacaj2am** [comment]
Great, that helped... :-)

was not aware of such a trick. Thank you (I feel that `src/platform/pico/*` files should come from platformio, ant they shouldn't be part of the project...). Need to diff them to check, if there are some changes.
